"""added box table

Revision ID: 2998f8df0299
Revises: b86bc9f86cd5
Create Date: 2021-07-07 12:32:58.539135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2998f8df0299'
down_revision = 'b86bc9f86cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boxreg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('club', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('pilot_lat', sa.Float(), nullable=True),
    sa.Column('pilot_long', sa.Float(), nullable=True),
    sa.Column('pilot_heading', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('log', sa.Column('boxreg_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'log', 'boxreg', ['boxreg_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'log', type_='foreignkey')
    op.drop_column('log', 'boxreg_id')
    op.drop_table('boxreg')
    # ### end Alembic commands ###
